export default {
  // Counter
  INCREMENT_COUNTER: 'INCREMENT_COUNTER',
  DECREMENT_COUNTER: 'DECREMENT_COUNTER',
  LOAD_APPLICANT_SUCCESS: 'LOAD_APPLICANT_SUCCESS',
  LOAD_APPLICANT_FAILURE: 'LOAD_APPLICANT_FAILURE',
  CLEAR_APPLICANT: 'CLEAR_APPLICANT',
  RESUME_UPLOAD_SUCCESS: 'RESUME_UPLOAD_SUCCESS'
}
